"""Recommendation tables

Revision ID: c856d47342da
Revises: 
Create Date: 2022-11-16 14:51:37.528603

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c856d47342da"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "goal_updates",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("journey_id", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "platform_statuses",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("recommendation_id", sa.BigInteger(), nullable=False),
        sa.Column("platform", sa.Text(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_platform_statuses_recommendation_id"), "platform_statuses", ["recommendation_id"], unique=False
    )
    op.create_table(
        "recommendations",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("uuid", postgresql.UUID(), nullable=False),
        sa.Column("creation_date", sa.DateTime(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("journey_id", sa.BigInteger(), nullable=False),
        sa.Column("media_plan_id", sa.BigInteger(), nullable=True),
        sa.Column("journey_name", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("taxonomy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("decision_time", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(
        "ix_recommendations_account_id_order",
        "recommendations",
        [
            "account_id",
            sa.text("(status = 'ACTIVE') DESC"),
            sa.text("creation_date DESC"),
            sa.text("id DESC"),
        ],
        unique=False,
    )
    op.create_index(
        "ix_recommendations_account_id_date_order",
        "recommendations",
        ["account_id", sa.text("creation_date DESC"), sa.text("id DESC")],
        unique=False,
    )
    op.create_index("ix_recommendations_account_id_status", "recommendations", ["account_id", "status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_recommendations_account_id_status", table_name="recommendations")
    op.drop_index("ix_recommendations_account_id_date_order", table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_platform_statuses_recommendation_id"), table_name="platform_statuses")
    op.drop_table("platform_statuses")
    op.drop_table("goal_updates")
    # ### end Alembic commands ###
